# Generated by Django 4.2 on 2024-07-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_colorvariant_sizevariant_product_size_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorvariant',
            name='color_price',
            field=models.IntegerField(default=1),
        ),
    ]
