# Generated by Django 4.2 on 2024-07-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_colorvariant_color_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_variant',
            field=models.ManyToManyField(blank=True, related_name='size_variants', to='products.sizevariant'),
        ),
    ]
