# Generated by Django 4.2 on 2024-07-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cart_cartitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qunatity',
            field=models.IntegerField(default=0),
        ),
    ]
